//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.05 at 08:50:12 PM SAMT 
//


package ru.fsrar.wegais.commonv3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Запись в справке 2 к ТТН, Информация о предыдущих отгрузках
 * 
 * <p>Java class for InformF2TypeItemBC complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InformF2TypeItemBC">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="F2RegId" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50"/>
 *         &lt;element name="MarkInfo" type="{http://fsrar.ru/WEGAIS/CommonV3}MarkInfoTypeBC" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InformF2TypeItemBC", propOrder = {
    "f2RegId",
    "markInfo"
})
public class InformF2TypeItemBC {

    @XmlElement(name = "F2RegId", required = true, defaultValue = "FIRSTSHIPMENT")
    protected String f2RegId;
    @XmlElement(name = "MarkInfo")
    protected MarkInfoTypeBC markInfo;

    /**
     * Gets the value of the f2RegId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getF2RegId() {
        return f2RegId;
    }

    /**
     * Sets the value of the f2RegId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setF2RegId(String value) {
        this.f2RegId = value;
    }

    /**
     * Gets the value of the markInfo property.
     * 
     * @return
     *     possible object is
     *     {@link MarkInfoTypeBC }
     *     
     */
    public MarkInfoTypeBC getMarkInfo() {
        return markInfo;
    }

    /**
     * Sets the value of the markInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarkInfoTypeBC }
     *     
     */
    public void setMarkInfo(MarkInfoTypeBC value) {
        this.markInfo = value;
    }

}
