//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.05 at 08:50:12 PM SAMT 
//


package ru.fsrar.wegais.commonv3;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.fsrar.wegais.commonv3 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BoxtypeBl_QNAME = new QName("http://fsrar.ru/WEGAIS/CommonV3", "bl");
    private final static QName _BoxtypeBoxnum_QNAME = new QName("http://fsrar.ru/WEGAIS/CommonV3", "boxnum");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.fsrar.wegais.commonv3
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AMCforDocType }
     * 
     */
    public AMCforDocType createAMCforDocType() {
        return new AMCforDocType();
    }

    /**
     * Create an instance of {@link MarkInfoTypeBC }
     * 
     */
    public MarkInfoTypeBC createMarkInfoTypeBC() {
        return new MarkInfoTypeBC();
    }

    /**
     * Create an instance of {@link InformF2TypeItemBC }
     * 
     */
    public InformF2TypeItemBC createInformF2TypeItemBC() {
        return new InformF2TypeItemBC();
    }

    /**
     * Create an instance of {@link Bktype }
     * 
     */
    public Bktype createBktype() {
        return new Bktype();
    }

    /**
     * Create an instance of {@link BoxamcType }
     * 
     */
    public BoxamcType createBoxamcType() {
        return new BoxamcType();
    }

    /**
     * Create an instance of {@link Boxtype }
     * 
     */
    public Boxtype createBoxtype() {
        return new Boxtype();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boxtype }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/CommonV3", name = "bl", scope = Boxtype.class)
    public JAXBElement<Boxtype> createBoxtypeBl(Boxtype value) {
        return new JAXBElement<Boxtype>(_BoxtypeBl_QNAME, Boxtype.class, Boxtype.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/CommonV3", name = "boxnum", scope = Boxtype.class)
    public JAXBElement<String> createBoxtypeBoxnum(String value) {
        return new JAXBElement<String>(_BoxtypeBoxnum_QNAME, String.class, Boxtype.class, value);
    }

}
