//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.05 at 08:50:12 PM SAMT 
//


package ru.fsrar.wegais.clientref_v2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.fsrar.wegais.clientref_v2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TSTypeTSNUM_QNAME = new QName("http://fsrar.ru/WEGAIS/ClientRef_v2", "TSNUM");
    private final static QName _OrgInfoExV2State_QNAME = new QName("http://fsrar.ru/WEGAIS/ClientRef_v2", "State");
    private final static QName _OrgInfoExV2IsLicense_QNAME = new QName("http://fsrar.ru/WEGAIS/ClientRef_v2", "isLicense");
    private final static QName _OrgInfoExV2VersionWB_QNAME = new QName("http://fsrar.ru/WEGAIS/ClientRef_v2", "VersionWB");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.fsrar.wegais.clientref_v2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OrgInfoExV2 }
     * 
     */
    public OrgInfoExV2 createOrgInfoExV2() {
        return new OrgInfoExV2();
    }

    /**
     * Create an instance of {@link OrgAddressTypeFOTS }
     * 
     */
    public OrgAddressTypeFOTS createOrgAddressTypeFOTS() {
        return new OrgAddressTypeFOTS();
    }

    /**
     * Create an instance of {@link TSType }
     * 
     */
    public TSType createTSType() {
        return new TSType();
    }

    /**
     * Create an instance of {@link OrgItemType }
     * 
     */
    public OrgItemType createOrgItemType() {
        return new OrgItemType();
    }

    /**
     * Create an instance of {@link ULType }
     * 
     */
    public ULType createULType() {
        return new ULType();
    }

    /**
     * Create an instance of {@link OrganizationsType }
     * 
     */
    public OrganizationsType createOrganizationsType() {
        return new OrganizationsType();
    }

    /**
     * Create an instance of {@link FOType }
     * 
     */
    public FOType createFOType() {
        return new FOType();
    }

    /**
     * Create an instance of {@link OrgInfoV2 }
     * 
     */
    public OrgInfoV2 createOrgInfoV2() {
        return new OrgInfoV2();
    }

    /**
     * Create an instance of {@link ProductContractType }
     * 
     */
    public ProductContractType createProductContractType() {
        return new ProductContractType();
    }

    /**
     * Create an instance of {@link FLType }
     * 
     */
    public FLType createFLType() {
        return new FLType();
    }

    /**
     * Create an instance of {@link OrgInfoRusReplyV2 }
     * 
     */
    public OrgInfoRusReplyV2 createOrgInfoRusReplyV2() {
        return new OrgInfoRusReplyV2();
    }

    /**
     * Create an instance of {@link OrgInfoReplyV2 }
     * 
     */
    public OrgInfoReplyV2 createOrgInfoReplyV2() {
        return new OrgInfoReplyV2();
    }

    /**
     * Create an instance of {@link FLReplyType }
     * 
     */
    public FLReplyType createFLReplyType() {
        return new FLReplyType();
    }

    /**
     * Create an instance of {@link OrgAddressTypeULFLReply }
     * 
     */
    public OrgAddressTypeULFLReply createOrgAddressTypeULFLReply() {
        return new OrgAddressTypeULFLReply();
    }

    /**
     * Create an instance of {@link OrgInfoForeignV2 }
     * 
     */
    public OrgInfoForeignV2 createOrgInfoForeignV2() {
        return new OrgInfoForeignV2();
    }

    /**
     * Create an instance of {@link TSReplyType }
     * 
     */
    public TSReplyType createTSReplyType() {
        return new TSReplyType();
    }

    /**
     * Create an instance of {@link ULReplyType }
     * 
     */
    public ULReplyType createULReplyType() {
        return new ULReplyType();
    }

    /**
     * Create an instance of {@link OrgInfoForeignReplyV2 }
     * 
     */
    public OrgInfoForeignReplyV2 createOrgInfoForeignReplyV2() {
        return new OrgInfoForeignReplyV2();
    }

    /**
     * Create an instance of {@link OrgAddressTypeULFL }
     * 
     */
    public OrgAddressTypeULFL createOrgAddressTypeULFL() {
        return new OrgAddressTypeULFL();
    }

    /**
     * Create an instance of {@link OrgInfoRusV2 }
     * 
     */
    public OrgInfoRusV2 createOrgInfoRusV2() {
        return new OrgInfoRusV2();
    }

    /**
     * Create an instance of {@link OrgAddressType }
     * 
     */
    public OrgAddressType createOrgAddressType() {
        return new OrgAddressType();
    }

    /**
     * Create an instance of {@link OrgInfoExV2 .Addresslist }
     * 
     */
    public OrgInfoExV2 .Addresslist createOrgInfoExV2Addresslist() {
        return new OrgInfoExV2 .Addresslist();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef_v2", name = "TSNUM", scope = TSType.class)
    public JAXBElement<String> createTSTypeTSNUM(String value) {
        return new JAXBElement<String>(_TSTypeTSNUM_QNAME, String.class, TSType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef_v2", name = "State", scope = OrgInfoExV2 .class)
    public JAXBElement<String> createOrgInfoExV2State(String value) {
        return new JAXBElement<String>(_OrgInfoExV2State_QNAME, String.class, OrgInfoExV2 .class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef_v2", name = "isLicense", scope = OrgInfoExV2 .class)
    public JAXBElement<Boolean> createOrgInfoExV2IsLicense(Boolean value) {
        return new JAXBElement<Boolean>(_OrgInfoExV2IsLicense_QNAME, Boolean.class, OrgInfoExV2 .class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef_v2", name = "VersionWB", scope = OrgInfoExV2 .class)
    public JAXBElement<String> createOrgInfoExV2VersionWB(String value) {
        return new JAXBElement<String>(_OrgInfoExV2VersionWB_QNAME, String.class, OrgInfoExV2 .class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef_v2", name = "TSNUM", scope = TSReplyType.class)
    public JAXBElement<String> createTSReplyTypeTSNUM(String value) {
        return new JAXBElement<String>(_TSTypeTSNUM_QNAME, String.class, TSReplyType.class, value);
    }

}
