//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.05 at 08:50:12 PM SAMT 
//


package ru.fsrar.wegais.clientref_v2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrgInfoEx_v2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrgInfoEx_v2">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Identity" type="{http://fsrar.ru/WEGAIS/Common}IdentityType" minOccurs="0"/>
 *         &lt;element name="OrgInfoV2" type="{http://fsrar.ru/WEGAIS/ClientRef_v2}OrgInfoReply_v2"/>
 *         &lt;element name="addresslist" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="address" type="{http://fsrar.ru/WEGAIS/ClientRef_v2}OrgAddressType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VersionWB" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50" minOccurs="0"/>
 *         &lt;element name="isLicense" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrgInfoEx_v2", propOrder = {

})
public class OrgInfoExV2 {

    @XmlElement(name = "Identity")
    protected String identity;
    @XmlElement(name = "OrgInfoV2", required = true)
    protected OrgInfoReplyV2 orgInfoV2;
    protected OrgInfoExV2 .Addresslist addresslist;
    @XmlElementRef(name = "State", namespace = "http://fsrar.ru/WEGAIS/ClientRef_v2", type = JAXBElement.class, required = false)
    protected JAXBElement<String> state;
    @XmlElementRef(name = "VersionWB", namespace = "http://fsrar.ru/WEGAIS/ClientRef_v2", type = JAXBElement.class, required = false)
    protected JAXBElement<String> versionWB;
    @XmlElementRef(name = "isLicense", namespace = "http://fsrar.ru/WEGAIS/ClientRef_v2", type = JAXBElement.class, required = false)
    protected JAXBElement<Boolean> isLicense;

    /**
     * Gets the value of the identity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * Sets the value of the identity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentity(String value) {
        this.identity = value;
    }

    /**
     * Gets the value of the orgInfoV2 property.
     * 
     * @return
     *     possible object is
     *     {@link OrgInfoReplyV2 }
     *     
     */
    public OrgInfoReplyV2 getOrgInfoV2() {
        return orgInfoV2;
    }

    /**
     * Sets the value of the orgInfoV2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrgInfoReplyV2 }
     *     
     */
    public void setOrgInfoV2(OrgInfoReplyV2 value) {
        this.orgInfoV2 = value;
    }

    /**
     * Gets the value of the addresslist property.
     * 
     * @return
     *     possible object is
     *     {@link OrgInfoExV2 .Addresslist }
     *     
     */
    public OrgInfoExV2 .Addresslist getAddresslist() {
        return addresslist;
    }

    /**
     * Sets the value of the addresslist property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrgInfoExV2 .Addresslist }
     *     
     */
    public void setAddresslist(OrgInfoExV2 .Addresslist value) {
        this.addresslist = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setState(JAXBElement<String> value) {
        this.state = value;
    }

    /**
     * Gets the value of the versionWB property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getVersionWB() {
        return versionWB;
    }

    /**
     * Sets the value of the versionWB property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setVersionWB(JAXBElement<String> value) {
        this.versionWB = value;
    }

    /**
     * Gets the value of the isLicense property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public JAXBElement<Boolean> getIsLicense() {
        return isLicense;
    }

    /**
     * Sets the value of the isLicense property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public void setIsLicense(JAXBElement<Boolean> value) {
        this.isLicense = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="address" type="{http://fsrar.ru/WEGAIS/ClientRef_v2}OrgAddressType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "address"
    })
    public static class Addresslist {

        @XmlElement(required = true)
        protected List<OrgAddressType> address;

        /**
         * Gets the value of the address property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the address property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAddress().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OrgAddressType }
         * 
         * 
         */
        public List<OrgAddressType> getAddress() {
            if (address == null) {
                address = new ArrayList<OrgAddressType>();
            }
            return this.address;
        }

    }

}
