//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.05 at 08:50:12 PM SAMT 
//


package ru.fsrar.wegais.clientref_v2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Российские организации
 * 
 * <p>Java class for OrgInfoRus_v2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrgInfoRus_v2">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="UL" type="{http://fsrar.ru/WEGAIS/ClientRef_v2}ULType"/>
 *         &lt;element name="FL" type="{http://fsrar.ru/WEGAIS/ClientRef_v2}FLType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrgInfoRus_v2", propOrder = {
    "ul",
    "fl"
})
public class OrgInfoRusV2 {

    @XmlElement(name = "UL")
    protected ULType ul;
    @XmlElement(name = "FL")
    protected FLType fl;

    /**
     * Gets the value of the ul property.
     * 
     * @return
     *     possible object is
     *     {@link ULType }
     *     
     */
    public ULType getUL() {
        return ul;
    }

    /**
     * Sets the value of the ul property.
     * 
     * @param value
     *     allowed object is
     *     {@link ULType }
     *     
     */
    public void setUL(ULType value) {
        this.ul = value;
    }

    /**
     * Gets the value of the fl property.
     * 
     * @return
     *     possible object is
     *     {@link FLType }
     *     
     */
    public FLType getFL() {
        return fl;
    }

    /**
     * Sets the value of the fl property.
     * 
     * @param value
     *     allowed object is
     *     {@link FLType }
     *     
     */
    public void setFL(FLType value) {
        this.fl = value;
    }

}
