//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.05 at 08:50:12 PM SAMT 
//


package ru.fsrar.wegais.replywriteoffcheque;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Ответ на запрос о количестве списаний по чекам
 * 
 * <p>Java class for ReplyWOCheque complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReplyWOCheque">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="ReplyDate" type="{http://fsrar.ru/WEGAIS/Common}DateWTime"/>
 *         &lt;element name="monthReport" type="{http://fsrar.ru/WEGAIS/Common}MonthType"/>
 *         &lt;element name="yearReport" type="{http://fsrar.ru/WEGAIS/Common}YearType"/>
 *         &lt;element name="AlcCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://fsrar.ru/WEGAIS/Common}NoEmptyString">
 *               &lt;maxLength value="64"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="WriteOffCh" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="ReturnCh" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReplyWOCheque", propOrder = {

})
public class ReplyWOCheque {

    @XmlElement(name = "ReplyDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar replyDate;
    @XmlElement(required = true)
    protected String monthReport;
    @XmlElement(required = true)
    protected String yearReport;
    @XmlElement(name = "AlcCode", required = true)
    protected String alcCode;
    @XmlElement(name = "WriteOffCh", required = true)
    protected BigInteger writeOffCh;
    @XmlElement(name = "ReturnCh", required = true)
    protected BigInteger returnCh;

    /**
     * Gets the value of the replyDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReplyDate() {
        return replyDate;
    }

    /**
     * Sets the value of the replyDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReplyDate(XMLGregorianCalendar value) {
        this.replyDate = value;
    }

    /**
     * Gets the value of the monthReport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMonthReport() {
        return monthReport;
    }

    /**
     * Sets the value of the monthReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMonthReport(String value) {
        this.monthReport = value;
    }

    /**
     * Gets the value of the yearReport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYearReport() {
        return yearReport;
    }

    /**
     * Sets the value of the yearReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYearReport(String value) {
        this.yearReport = value;
    }

    /**
     * Gets the value of the alcCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlcCode() {
        return alcCode;
    }

    /**
     * Sets the value of the alcCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlcCode(String value) {
        this.alcCode = value;
    }

    /**
     * Gets the value of the writeOffCh property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWriteOffCh() {
        return writeOffCh;
    }

    /**
     * Sets the value of the writeOffCh property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWriteOffCh(BigInteger value) {
        this.writeOffCh = value;
    }

    /**
     * Gets the value of the returnCh property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getReturnCh() {
        return returnCh;
    }

    /**
     * Sets the value of the returnCh property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setReturnCh(BigInteger value) {
        this.returnCh = value;
    }

}
