//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.05 at 08:50:12 PM SAMT 
//


package ru.fsrar.wegais.asiiu;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import ru.fsrar.wegais.productref_v2.ProductInfoAsiiuV2;


/**
 * Строка данных измерений
 * 
 * <p>Java class for DataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Product" type="{http://fsrar.ru/WEGAIS/ProductRef_v2}ProductInfoAsiiu_v2"/>
 *         &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="VbsStart" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="VbsEnd" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="AStart" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="AEnd" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="PercentAlc" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="BottleCountStart" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="BottleCountEnd" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="Temperature" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="Mode" type="{http://fsrar.ru/WEGAIS/CommonEnum}ModeEnum"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataType", propOrder = {

})
public class DataType {

    @XmlElement(name = "Product", required = true)
    protected ProductInfoAsiiuV2 product;
    @XmlElement(name = "StartDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startDate;
    @XmlElement(name = "EndDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endDate;
    @XmlElement(name = "VbsStart", required = true)
    protected BigDecimal vbsStart;
    @XmlElement(name = "VbsEnd", required = true)
    protected BigDecimal vbsEnd;
    @XmlElement(name = "AStart", required = true)
    protected BigDecimal aStart;
    @XmlElement(name = "AEnd", required = true)
    protected BigDecimal aEnd;
    @XmlElement(name = "PercentAlc", required = true)
    protected BigDecimal percentAlc;
    @XmlElement(name = "BottleCountStart", required = true)
    protected BigDecimal bottleCountStart;
    @XmlElement(name = "BottleCountEnd", required = true)
    protected BigDecimal bottleCountEnd;
    @XmlElement(name = "Temperature", required = true)
    protected BigDecimal temperature;
    @XmlElement(name = "Mode", required = true)
    protected String mode;

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link ProductInfoAsiiuV2 }
     *     
     */
    public ProductInfoAsiiuV2 getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductInfoAsiiuV2 }
     *     
     */
    public void setProduct(ProductInfoAsiiuV2 value) {
        this.product = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the vbsStart property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVbsStart() {
        return vbsStart;
    }

    /**
     * Sets the value of the vbsStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVbsStart(BigDecimal value) {
        this.vbsStart = value;
    }

    /**
     * Gets the value of the vbsEnd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVbsEnd() {
        return vbsEnd;
    }

    /**
     * Sets the value of the vbsEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVbsEnd(BigDecimal value) {
        this.vbsEnd = value;
    }

    /**
     * Gets the value of the aStart property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAStart() {
        return aStart;
    }

    /**
     * Sets the value of the aStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAStart(BigDecimal value) {
        this.aStart = value;
    }

    /**
     * Gets the value of the aEnd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAEnd() {
        return aEnd;
    }

    /**
     * Sets the value of the aEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAEnd(BigDecimal value) {
        this.aEnd = value;
    }

    /**
     * Gets the value of the percentAlc property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPercentAlc() {
        return percentAlc;
    }

    /**
     * Sets the value of the percentAlc property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPercentAlc(BigDecimal value) {
        this.percentAlc = value;
    }

    /**
     * Gets the value of the bottleCountStart property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBottleCountStart() {
        return bottleCountStart;
    }

    /**
     * Sets the value of the bottleCountStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBottleCountStart(BigDecimal value) {
        this.bottleCountStart = value;
    }

    /**
     * Gets the value of the bottleCountEnd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBottleCountEnd() {
        return bottleCountEnd;
    }

    /**
     * Sets the value of the bottleCountEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBottleCountEnd(BigDecimal value) {
        this.bottleCountEnd = value;
    }

    /**
     * Gets the value of the temperature property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTemperature() {
        return temperature;
    }

    /**
     * Sets the value of the temperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTemperature(BigDecimal value) {
        this.temperature = value;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMode(String value) {
        this.mode = value;
    }

}
