//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.05 at 08:50:12 PM SAMT 
//


package ru.fsrar.wegais.requestaddproducts;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import ru.fsrar.wegais.productref_v2.ProductType;


/**
 * Позиция
 * 
 * <p>Java class for RequestAddSSPPositionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestAddSSPPositionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="Producer" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50"/>
 *         &lt;element name="Type" type="{http://fsrar.ru/WEGAIS/ProductRef_v2}ProductType"/>
 *         &lt;element name="VidCode" type="{http://fsrar.ru/WEGAIS/CommonEnum}Digits3"/>
 *         &lt;element name="CountryCode" type="{http://fsrar.ru/WEGAIS/CommonEnum}Digits3"/>
 *         &lt;element name="FullName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ShortName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="64"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Unpacked_Flag" type="{http://fsrar.ru/WEGAIS/RequestAddProducts}UnpackedType"/>
 *         &lt;element name="Capacity" type="{http://fsrar.ru/WEGAIS/Common}PositiveDecimalType" minOccurs="0"/>
 *         &lt;element name="PERCENT_ALC" type="{http://fsrar.ru/WEGAIS/Common}PositiveDecimalType"/>
 *         &lt;element name="PERCENT_ALC_min" type="{http://fsrar.ru/WEGAIS/Common}PositiveDecimalType" minOccurs="0"/>
 *         &lt;element name="PERCENT_ALC_max" type="{http://fsrar.ru/WEGAIS/Common}PositiveDecimalType" minOccurs="0"/>
 *         &lt;element name="FRAPID" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestAddSSPPositionType", propOrder = {

})
public class RequestAddSSPPositionType {

    @XmlElement(name = "Producer", required = true)
    protected String producer;
    @XmlElement(name = "Type", required = true)
    @XmlSchemaType(name = "string")
    protected ProductType type;
    @XmlElement(name = "VidCode", required = true)
    protected String vidCode;
    @XmlElement(name = "CountryCode", required = true)
    protected String countryCode;
    @XmlElement(name = "FullName", required = true)
    protected String fullName;
    @XmlElement(name = "ShortName", required = true)
    protected String shortName;
    @XmlElement(name = "Unpacked_Flag", required = true)
    protected BigInteger unpackedFlag;
    @XmlElement(name = "Capacity")
    protected BigDecimal capacity;
    @XmlElement(name = "PERCENT_ALC", required = true)
    protected BigDecimal percentalc;
    @XmlElement(name = "PERCENT_ALC_min")
    protected BigDecimal percentalcMin;
    @XmlElement(name = "PERCENT_ALC_max")
    protected BigDecimal percentalcMax;
    @XmlElement(name = "FRAPID")
    protected String frapid;

    /**
     * Gets the value of the producer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProducer() {
        return producer;
    }

    /**
     * Sets the value of the producer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProducer(String value) {
        this.producer = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ProductType }
     *     
     */
    public ProductType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductType }
     *     
     */
    public void setType(ProductType value) {
        this.type = value;
    }

    /**
     * Gets the value of the vidCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVidCode() {
        return vidCode;
    }

    /**
     * Sets the value of the vidCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVidCode(String value) {
        this.vidCode = value;
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the fullName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * Sets the value of the fullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullName(String value) {
        this.fullName = value;
    }

    /**
     * Gets the value of the shortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * Sets the value of the shortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortName(String value) {
        this.shortName = value;
    }

    /**
     * Gets the value of the unpackedFlag property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUnpackedFlag() {
        return unpackedFlag;
    }

    /**
     * Sets the value of the unpackedFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUnpackedFlag(BigInteger value) {
        this.unpackedFlag = value;
    }

    /**
     * Gets the value of the capacity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCapacity() {
        return capacity;
    }

    /**
     * Sets the value of the capacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCapacity(BigDecimal value) {
        this.capacity = value;
    }

    /**
     * Gets the value of the percentalc property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPERCENTALC() {
        return percentalc;
    }

    /**
     * Sets the value of the percentalc property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPERCENTALC(BigDecimal value) {
        this.percentalc = value;
    }

    /**
     * Gets the value of the percentalcMin property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPERCENTALCMin() {
        return percentalcMin;
    }

    /**
     * Sets the value of the percentalcMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPERCENTALCMin(BigDecimal value) {
        this.percentalcMin = value;
    }

    /**
     * Gets the value of the percentalcMax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPERCENTALCMax() {
        return percentalcMax;
    }

    /**
     * Sets the value of the percentalcMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPERCENTALCMax(BigDecimal value) {
        this.percentalcMax = value;
    }

    /**
     * Gets the value of the frapid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFRAPID() {
        return frapid;
    }

    /**
     * Sets the value of the frapid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFRAPID(String value) {
        this.frapid = value;
    }

}
