//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.05 at 08:50:12 PM SAMT 
//


package ru.fsrar.wegais.actchargeon;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Справки А и Б ссылки
 * 
 * <p>Java class for InformABKeyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InformABKeyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FormA" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50"/>
 *         &lt;element name="LastFormB" type="{http://fsrar.ru/WEGAIS/Common}NoEmptyString50"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InformABKeyType", propOrder = {
    "formA",
    "lastFormB"
})
public class InformABKeyType {

    @XmlElement(name = "FormA", required = true)
    protected String formA;
    @XmlElement(name = "LastFormB", required = true)
    protected String lastFormB;

    /**
     * Gets the value of the formA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormA() {
        return formA;
    }

    /**
     * Sets the value of the formA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormA(String value) {
        this.formA = value;
    }

    /**
     * Gets the value of the lastFormB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastFormB() {
        return lastFormB;
    }

    /**
     * Sets the value of the lastFormB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastFormB(String value) {
        this.lastFormB = value;
    }

}
