//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.05 at 08:50:12 PM SAMT 
//


package ru.fsrar.wegais.clientref;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.fsrar.wegais.clientref package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OrgInfoINN_QNAME = new QName("http://fsrar.ru/WEGAIS/ClientRef", "INN");
    private final static QName _OrgInfoRNN_QNAME = new QName("http://fsrar.ru/WEGAIS/ClientRef", "RNN");
    private final static QName _OrgInfoUNP_QNAME = new QName("http://fsrar.ru/WEGAIS/ClientRef", "UNP");
    private final static QName _OrgInfoExState_QNAME = new QName("http://fsrar.ru/WEGAIS/ClientRef", "State");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.fsrar.wegais.clientref
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OrgInfoEx }
     * 
     */
    public OrgInfoEx createOrgInfoEx() {
        return new OrgInfoEx();
    }

    /**
     * Create an instance of {@link OrgLicenseType }
     * 
     */
    public OrgLicenseType createOrgLicenseType() {
        return new OrgLicenseType();
    }

    /**
     * Create an instance of {@link OrgInfo }
     * 
     */
    public OrgInfo createOrgInfo() {
        return new OrgInfo();
    }

    /**
     * Create an instance of {@link ProductContractType }
     * 
     */
    public ProductContractType createProductContractType() {
        return new ProductContractType();
    }

    /**
     * Create an instance of {@link OrganizationsType }
     * 
     */
    public OrganizationsType createOrganizationsType() {
        return new OrganizationsType();
    }

    /**
     * Create an instance of {@link OrgItemType }
     * 
     */
    public OrgItemType createOrgItemType() {
        return new OrgItemType();
    }

    /**
     * Create an instance of {@link OrgAddressType }
     * 
     */
    public OrgAddressType createOrgAddressType() {
        return new OrgAddressType();
    }

    /**
     * Create an instance of {@link OrgInfoEx.Addresslist }
     * 
     */
    public OrgInfoEx.Addresslist createOrgInfoExAddresslist() {
        return new OrgInfoEx.Addresslist();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef", name = "INN", scope = OrgInfo.class)
    public JAXBElement<String> createOrgInfoINN(String value) {
        return new JAXBElement<String>(_OrgInfoINN_QNAME, String.class, OrgInfo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef", name = "RNN", scope = OrgInfo.class)
    public JAXBElement<String> createOrgInfoRNN(String value) {
        return new JAXBElement<String>(_OrgInfoRNN_QNAME, String.class, OrgInfo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef", name = "UNP", scope = OrgInfo.class)
    public JAXBElement<String> createOrgInfoUNP(String value) {
        return new JAXBElement<String>(_OrgInfoUNP_QNAME, String.class, OrgInfo.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef", name = "INN", scope = OrgInfoEx.class)
    public JAXBElement<String> createOrgInfoExINN(String value) {
        return new JAXBElement<String>(_OrgInfoINN_QNAME, String.class, OrgInfoEx.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef", name = "RNN", scope = OrgInfoEx.class)
    public JAXBElement<String> createOrgInfoExRNN(String value) {
        return new JAXBElement<String>(_OrgInfoRNN_QNAME, String.class, OrgInfoEx.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef", name = "UNP", scope = OrgInfoEx.class)
    public JAXBElement<String> createOrgInfoExUNP(String value) {
        return new JAXBElement<String>(_OrgInfoUNP_QNAME, String.class, OrgInfoEx.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fsrar.ru/WEGAIS/ClientRef", name = "State", scope = OrgInfoEx.class)
    public JAXBElement<String> createOrgInfoExState(String value) {
        return new JAXBElement<String>(_OrgInfoExState_QNAME, String.class, OrgInfoEx.class, value);
    }

}
